from .K3NKImageGrab import NODE_CLASS_MAPPINGS as GRAB_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GRAB_DISPLAY
from .k3nk_image_loader_with_blending import NODE_CLASS_MAPPINGS as BLEND_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BLEND_DISPLAY
from .save_latent_node import NODE_CLASS_MAPPINGS as LATENT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LATENT_DISPLAY

NODE_CLASS_MAPPINGS = {**GRAB_MAPPINGS, **BLEND_MAPPINGS, **LATENT_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**GRAB_DISPLAY, **BLEND_DISPLAY, **LATENT_DISPLAY}
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
