from .K3NKImageGrab import NODE_CLASS_MAPPINGS as GRAB_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GRAB_DISPLAY
from .k3nk_image_loader_with_blending import NODE_CLASS_MAPPINGS as BLEND_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BLEND_DISPLAY
from .save_latent_node import NODE_CLASS_MAPPINGS as LATENT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LATENT_DISPLAY
from .k3nk_find_nearest_bucket import NODE_CLASS_MAPPINGS as BUCKET_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as BUCKET_DISPLAY
from .k3nk_image_overlay import NODE_CLASS_MAPPINGS as OVERLAY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OVERLAY_DISPLAY
from .k3nk_video_loader_from_dir import NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY
from .k3nk_text_loader import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY
from .k3nk_video_concat_simple import NODE_CLASS_MAPPINGS as SIMPLE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_DISPLAY
from .k3nk_save_compress import NODE_CLASS_MAPPINGS as COMPRESS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as COMPRESS_DISPLAY

NODE_CLASS_MAPPINGS = {**GRAB_MAPPINGS, **BLEND_MAPPINGS, **LATENT_MAPPINGS, **BUCKET_MAPPINGS, **OVERLAY_MAPPINGS, **VIDEO_MAPPINGS, **TEXT_MAPPINGS, **SIMPLE_MAPPINGS, **COMPRESS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**GRAB_DISPLAY, **BLEND_DISPLAY, **LATENT_DISPLAY, **BUCKET_DISPLAY, **OVERLAY_DISPLAY, **VIDEO_DISPLAY, **TEXT_DISPLAY, **SIMPLE_DISPLAY, **COMPRESS_DISPLAY}
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
